inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - lib/arfi/extensions/active_record/connection_adapters/postgresql/database_statements.rb
    - 'vendor/**/*'
plugins:
  - rubocop-sorted_methods_by_call
  - rubocop-rspec

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec
