module ActiveRecord
  class Base
    # +ActiveRecord::Base.function_exists?+               -> bool
    #
    # This method checks if a custom SQL function exists in the database.
    #
    # @example
    #   ActiveRecord::Base.function_exists?('my_function') #=> true
    #   ActiveRecord::Base.function_exists?('my_function123') #=> false
    # @param [String] function_name The name of the function to check.
    # @return [Boolean] Returns true if the function exists, false otherwise.
    def self.function_exists?: (string function_name) -> bool
  end
end
