module ActiveRecord
  class Base
    def self.function_exists?: (String function_name) -> bool

    def self.pg_function_exists?: (String function_name) -> bool

    def self.mysql_function_exists?: (String function_name) -> bool

    def self.trigger_exists?: (String table, String trigger_name) -> bool

    def self.pg_trigger_exists?: (String table, String trigger_name) -> bool

    def self.mysql_trigger_exists?: (String table, String trigger_name) -> bool

    def self.function_source: (String function_name, ?schema: String?) -> String?

    def self.pg_function_source: (String function_name, ?schema: String?) -> String?

    def self.mysql_function_source: (String function_name) -> String?
  end
end
