module ActiveRecord
  class Base
    def self.function_exists?: (String function_name) -> bool

    def self.pg_function_exists?: (String function_name) -> bool

    def self.mysql_function_exists?: (String function_name) -> bool
  end
end
