module Arfi
  module Commands
    class Project
      # @return [void]
      def create: () -> void

      private

      # @private
      # @return [Pathname] Path to `db/functions` directory
      def functions_dir: () -> Pathname
    end
  end
end
