module Arfi
  module Commands
    module TriggersRendering : Arfi::Commands::Triggers
      private

      def render_list: (Array[::Hash[Symbol, untyped]] rows) -> void

      def print_table: (Array[resolved_row] rows) -> void

      def table_columns: () -> Array[String]

      def stringify_rows: (Array[resolved_row] rows) -> Array[resolved_row]

      def calculate_widths: (Array[String] cols, Array[resolved_row] table) -> ::Hash[String, Integer]

      def render_table_rows: (Array[resolved_row] table, Array[String] cols, ::Hash[String, Integer] widths) -> void

      def resolve_key_group: (Array[candidate] arr) -> Array[::Hash[Symbol, untyped]]

      def all_mode_rows: (Array[candidate] arr, candidate chosen) -> Array[::Hash[Symbol, untyped]]

      def default_mode_row: (candidate chosen, Array[candidate] arr) -> Array[::Hash[Symbol, untyped]]
    end
  end
end
