module ActiveRecord
  class Base
    def self.connection_handler: () -> ::ActiveRecord::ConnectionAdapters::ConnectionHandler

    def self.clear_active_connections!: () -> void

    def self.configurations: () -> ::ActiveRecord::DatabaseConfigurations

    def self.connection_db_config: () -> ::ActiveRecord::DatabaseConfigurations::DatabaseConfig
  end

  class DatabaseConfigurations::DatabaseConfig
    def name: () -> ::String

    def env_name: () -> ::String

    def configuration_hash: () -> ::Hash[::Symbol | ::String, ::String | ::Integer | bool | nil]
  end
end
