name: Ruby Gem CI/CD

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Lint, Typecheck, and External Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '3.4.2'
    steps:
      - name: Checkout current project
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Run RuboCop
        run: bundle exec rubocop
      - name: Install RBS collection and run Steep
        run: |
          bundle exec rbs collection install
          bundle exec steep check
      - name: Clone external test project
        run: |
          git clone https://github.com/unurgunite/poc_arfi_72 external_specs
          cd external_specs
          chmod +x ./bin/test_case.sh
          bundle install
          ./bin/test_case.sh

  release:
    name: Release Gem to RubyGems
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
          bundler-cache: true
      - name: Build the gem
        run: gem build *.gemspec
      - name: Push to RubyGems
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: |
          gem install rubygems-release
          gem push *.gem
